#!/bin/bash

set -u
set -e
. "$GRML_LIVE_CONFIG"

# change shell back to bash

if $ROOTCMD [ -r /bin/bash ] ; then
   $ROOTCMD chsh -s /bin/bash root
   $ROOTCMD chsh -s /bin/bash $USERNAME
fi

cat <<EOF > $target/root/.bashrc
export LS_OPTIONS='--color=auto'
alias ls='ls \$LS_OPTIONS'
alias ll='ls \$LS_OPTIONS -l'
alias l='ls \$LS_OPTIONS -lA'
EOF

cat <<EOF > $target/home/$USERNAME/.bash_aliases
alias ll='ls -l'
alias l='ls -lA'
EOF

$ROOTCMD chown ${USERNAME}:${USERNAME} /home/${USERNAME}/.bash_aliases
